### ISSUE TITLE
Update go-plugin & Vault SDK to latest versions in order to support autoMTLS

### ISSUE THREAD

**Issue by paulternate** [Venafi/vault-pki-backend-venafi#121]
**BUSINESS PROBLEM**
When configuring the plugin against TLS Protect Datacenter, trust must be established between the Venafi and Vault servers. Establishing that trust is currently a manual process. 

**PROPOSED SOLUTION**
After updating the go-plugin and Vault SDK, autoMTLS will be enabled in the plugin and manually establishing trust will no longer be necessary. 

**CURRENT ALTERNATIVES**
Use a publicly trusted certificate for the Venafi Operational Certificate (uncommon), or manually establish trust by permanently adding the VOC CA Cert to the Vault trust store or referencing it with the `trust_bundle_file` parameter.

**Comment by luispresuelVenafi** [comment]
Hi @paulternate ,
It's safe to say that by "Update go-plugin & Vault SDK to latest versions", means to update the Golang currently handled in our plugin and the Vault SDK for plugin development to latest version? Or what does it mean the `go-plugin` in this context?

**Comment by paulternate** [comment]
@luispresuelVenafi - This is in reference to:
- [go-plugin](https://github.com/hashicorp/go-plugin)
- [Vault SDK](https://github.com/hashicorp/vault/tree/main/sdk)

**Comment by luispresuelVenafi** [comment]
Got it @luispresuelVenafi 

[go-plugin](https://github.com/hashicorp/go-plugin) is not explicitly defined in [go.mod](https://github.com/Venafi/vault-pki-backend-venafi/blob/master/go.mod), so that's why I didn't that we had that library, but I do see it as a dependency in [go.sum](https://github.com/Venafi/vault-pki-backend-venafi/blob/master/go.sum). This should be upgraded all together once we update our Hashicorp Vault SDK version
