### ISSUE TITLE
Add support for specifying trust bundles when connecting to VCloud

### ISSUE THREAD

**Issue by wgoulet** [Venafi/vault-pki-backend-venafi#28]
Hi,

A Venafi Cloud user recently attempted to use this plugin and received the following error:
`URL: PUT https://vault-test-example.com/v1/venafi-pki/issue/cloud-backend
Code: 400. Errors:

* failed to get Venafi issuer client: Get https://api.venafi.cloud/v1/useraccounts: x509: certificate signed by unknown authority
`
The user provided additional debug logs which indicate that a SSL interception device is in use for connections to api.venafi.cloud. As a result, the issuing chain for api.venafi.cloud from the plugin's perspective is not trusted. Can the trust_bundle option supported for connections to TPP be added for connections to the Cloud endpoint?

Thanks,
Walter

**Comment by marcpascual** [comment]
Hi Walter,

Thanks for opening the issue. Another somewhat-related feature that would be useful is to be able to skip tls verification. This is especially helpful in testing orchestrated environments (e.g. spin up dynamic ssl-intercepting proxies) using self-signed certificates. 

regards,
Marc

**Comment by wgoulet** [comment]
Hi @marcpascual ,

My fellow PM will be replying back with thoughts on adding support for specifying a truststore for connections to Cloud as well as thoughts on disabling verification.

In the meantime, I wanted to suggest a possible workaround. I'm unsure how you are running your Vault instance, but if it is running in a container you could potentially use a Dockerfile to copy the certificate to the truststore of the Linux OS running Vault and putting it in the correct location, then executing update-ca-trust (or equivalent command for your Linux distro) to properly update the truststore. This would at least unblock you and allow you to test the core functionality while we consider updates to vcert itself.

Thanks,
Walter

**Comment by tr1ck3r** [comment]
Hi @marcpascual,

We already have trust store support in our VCert libraries for the Venafi Platform so I don't expect it will be too difficult to make it a general feature that applies to both Platform and Cloud.  We're working on a few high priority things right now but I think we'll be able to get it added in Q3.  It's honestly a case we didn't anticipate for Cloud because it will always have a publicly trusted certificate securing its web services.  The suggestion that @wgoulet made has worked for me in the past when our solutions were under development and had not yet implemented the trust store logic so I hope that does indeed get you unblocked.

Thanks!
Ryan

**Comment by marcpascual** [comment]
hi @tr1ck3r @wgoulet, 

Thanks for your suggestion. I tried adding / overriding the default trust store on the docker image and it works.

regards,
Marc

**Comment by da-edra** [comment]
Hello, I'm having this issue too.
Are there any updates on this matter?
