### ISSUE TITLE
TTL and MaxTTL have no effect - Add support for variable certificate validity

### ISSUE THREAD

**Issue by mbrancato** [Venafi/vault-pki-backend-venafi#49]
**PROBLEM SUMMARY**

We're trying to use this plugin with a command like:

```
vault write mount/venafi/pki/myrole common_name=mycert.mydomain.example ttl=288h
```

And there are several problems:

1. The max_ttl of the PKI role is not enforced
1. The ttl and max_ttl of the role seem to have no effect
1. The returned ttl seems to be based only on the Venafi "template" for the provider. Again, the client's specified ttl seems to be ignored.

**STEPS TO REPRODUCE**

```
vault write venafi/pki/roles/myrole \
generate_lease=true \
store_by_cn=true \
store_pkey=true \
tpp_user=xxx \
tpp_password=xxx \
zone='mypath\myzone' \
tpp_url='https://venafi-host:443/VEDSDK' \
ttl=720h \
max_ttl=720h

vault write venafi/pki/myrole common_name=mycert.mydomain.example ttl=900h
```

**EXPECTED RESULTS**

The ttl should be honored - the duration of the certificate should be equal to the ttl
when the requested ttl > max_ttl - request is rejected, no request made to Venafi

**ACTUAL RESULTS**

ttl and max_ttl in the role and the request seem to be ignored. This seems related to #33 .

**ENVIRONMENT DETAILS**
Vault 1.2.2, backend 0.5.2

**COMMENTS/WORKAROUNDS**

It looks like support is needed for the CA specific attributes `CASpecificAttributes` - but how can these vary based on the role / request?

**Comment by tr1ck3r** [comment]
Hi @mbrancato, yes, you're correct that the current implementation of this secrets engine is not designed to make use of the Vault `ttl` parameter.  The `ttl` value of the certificate stored in Vault will exactly align with the validity of the issued certificate which is controlled by the Trust Protection Platform CA template settings or the configuration of the CA itself.  As such the `max_ttl` value should be >= to the validity period of the certificates issued by the target CA.

We are exploring the possibility of adding support for this use case in the future but it will require updates to TPP that are not on the 2020 product roadmap.  Support for the feature would vary by CA driver; the following TPP drivers currently support the required "Specific End Date" functionality: DigiCert CertCentral, Entrust Certificate Services, Microsoft ADCS and Symantec/DigiCert MPKI.

**Comment by mbrancato** [comment]
Thanks for confirming @tr1ck3r 

Is there some way that a field could be added to the PKI role to support the CASpecificAttributes? It would help achieve our goals because the default templates seem to be very non-flexible such as only allowing 1 or 2 year defaults.

**Comment by tr1ck3r** [comment]
You're welcome, @mbrancato.  `CASpecificAttributes`, while flexible, is actually the opposite of what we are striving for with our DevOps integrations, VCert SDKs, and purpose-built REST API methods.  The reason is twofold.  First, a certificate requester would not be successful with the feature without consulting Venafi documentation or having a good handle on how Venafi products work.  Second, and more importantly, because the Trust Protection Platform schema was designed to be loosely typed, allowing the ability to assign values to attributes arbitrarily provides an avenue for data corruption and product instability.

I'm assuming based on your response you are using either our Entrust or Symantec MPKI drivers.  For several years we have been encouraging our public CA partners to add support for standard sub-year validity periods but they have not delivered anything other than the feature that allows individual certificate requests to specify specific end dates (which sacrifices renewal and reissuance functionality).  Browser makers including [Google](https://www.zdnet.com/article/google-wants-to-reduce-lifespan-for-https-certificates-to-one-year/) and more recently [Apple](https://support.apple.com/en-us/HT211025) have been pressuring CAs to reduce their standard certificate validity periods so it appears only a matter of time before sub-year validity comes to fruition.

If you or your organization are interested in contributing updates to this project and the VCert-Go to support this use case please [email me directly](mailto:ryan.treat@venafi.com) and I will provide you some guidance on how it would need to be implemented.  If not, I anticipate Venafi Engineering will be able to deliver this enhancement by the end of this year based on the current backlog and prioritization.

**Comment by mbrancato** [comment]
I understand the problem is challenging @tr1ck3r. I'm was just suggesting a stop-gap, but I thought is the Vault admin could configure a PKI role param for `ca_specific_attributes` or similar, then the client wouldn't need to know about TPP. But that does mean the admin would need to reconfigure those if the backend CA changed.

I'm definitely open to other options / solutions. An option may be applying a custom template and this might be another feature for the [Venafi Terraform provider](https://github.com/terraform-providers/terraform-provider-venafi). We already use a custom provider to implement https://github.com/terraform-providers/terraform-provider-venafi/issues/8. It might be worthwhile to work on adding both of these enhancements to this provider.

You're on-point for the overall goal. We're looking for short certs and largely this is to support both immutable / cloud infrastructure and to stay ahead of future cert lifetime limits. As you mention, Apple is basically at a 13 month max.

**Comment by tr1ck3r** [comment]
VCert-Go enhancement this requires has been created: https://github.com/Venafi/vcert/issues/132
