### ISSUE TITLE
Mismatched Keys on Certificate in Vault

### ISSUE THREAD

**Issue by escher54** [Venafi/vault-pki-backend-venafi#97]
**PROBLEM SUMMARY**
Our Venafi instance is using Entrust CA GW and have a limit of 20 concurrent connections currently. To compensate for the 60 second TTL for the CSRs within Hashicorp Vault we have worked with the DevOps team to create retries after 5 or 10 seconds after receiving errors from Hashicorp vault. In our load tests with the retries we had some certificates returned where the public key did not match the private key. We dug into this issue and found some of the retries were happening while Venafi was in the middle of processing the first request and it had not errored out. Venafi ended up processing both certificates through the CA within seconds of each other. Unfortunately, the certificate that was returned to vault was the Frist requested certificate, but the private key was from the second request. It does not look like the backend tool does any validation to ensure that the Public key matches the Private Key, which should of returned an error to the pipeline.

**STEPS TO REPRODUCE**
Configure Entrust CA GW Template and configure it with 20 concurrent sessions. Create pipeline to generate 60 threads to request 25 individual certificates equaling around 1500 certs. If an error is returned from vault then retry certificate 5 seconds later.

**EXPECTED RESULTS**
vault-pki-backend-venafi tool would check the public key and private key to ensure they match, if no match discard certificate and return an error

**ACTUAL RESULTS**
Public Key and Private key do not match, it is stored in Vault and the pipeline receives a invalid cert.

**ENVIRONMENT DETAILS**
Versions used in environment:
Venafi: 20.3
vault-pki-backend-venafi: v0.9.0

**COMMENTS/WORKAROUNDS**
In this test we submitted enough certs that would force the retries to take action, which was 60 threads of 25 individual certs for a total of 1500 certificates. This is a extreme test, but the fact that the tool is not validating the keys it could cause an outage. With using a public CA there could be slow downs that this could happen with less requests, and want to avoid this in the future.

**Comment by tr1ck3r** [comment]
@escher54 just to confirm, this happens when you make multiple requests for certificates with the same common name, correct?  I'll need to verify with the TPP team but I don't think TPP should allow a certificate object that is actively processing a request (or is in error) to accept another request.  Only speculation but I can see a possibility where multiple CSRs could be submitted for the same certificate object simultaneously _before_ TPP has started processing the certificate.  Would that situation be possible in your tests?  Do you consider that to be a valid case (making multiple requests for the same certificate at effectively the same time)?

I think it is a good idea to implement the check verify the certificate and private key match.  It seems likely given your test results that you would see an even greater percentage of failed certificate requests with that in place.  So I think we need to investigate what causes this mismatch to happen and try to eliminate the opportunity for it to happen whether that be in the Vault secrets engine or in TPP.

**Comment by escher54** [comment]
@tr1ck3r We were not purposefully trying to submit two CSRs for the same common name. Unfortunately, due to the high amount of certs we pushed, the 20 concurrent sessions with Entrust, Queuing in Venafi, and Vault holding CSR in memory for 60 seconds this is what happened. Vault would end up reaching its 60 seconds and then sending an error to the pipeline, which would wait 5 seconds and retry. When vault sent the second CSR Venafi was still processing the first. Venafi ended up finished retrieving the certs within seconds of each other, but returned the first certificate and the second certificate was set as a historical certificate. If you would like to see the specific logs for one of these certificates, I could export it and send it to the opensource@venafi.com?

I do find it odd that Venafi would not have sent an error that it was already processing a certificate. I agree, that trying to prevent the possibility of a mismatched certificate being returned is good. 

As for the check to verify the certificate and private key match increasing the failed certificates, this would be expected since mismatch keys is an error and should cause a failure. This would be better than returning a bad certificate to the pipeline. I believe even if we resolve this possibility for a mismatched key issue, there is still a chance and to cover it within the tool is a good way to prevent this.

As for when the certificate are in error, Venafi will stop future requests and require a manual reset. It would be nice if there was a way to reset certs in error through the tool, but that was not the original reason for this post.

Thank you,

Trent Libby

**Comment by tr1ck3r** [comment]
I think the best we can do on the Vault side is to verify the certificate matches the private key we generated locally.  In the rare chance they don't, we'll return an error rather than outputting the certificate and private key, and we'll also discard the locally generated key pair so there's no remnants left in the vault.

**Comment by luispresuelVenafi** [comment]
This has been addressed in [release v0.10.3](https://github.com/Venafi/vault-pki-backend-venafi/releases/tag/v0.10.3)
